#!/usr/bin/env python3.5

import httplib2
import datetime
import subprocess
import argparse

from apiclient import discovery
from oauth2client.service_account import ServiceAccountCredentials

# argument parsing variable
parser = argparse.ArgumentParser()
parser.add_argument("username", type=str, help="process just a single user, use all for everyone in the company")
args = parser.parse_args()
users_ret = args.username


# Variables needed for the google calendar api authentication
Scopes = 'https://www.googleapis.com/auth/calendar'
Application_name = 'Caltool'
Cred_file = '<insert credfile here>
Credentials = ServiceAccountCredentials.from_json_keyfile_name(Cred_file, scopes=Scopes)
Now = datetime.datetime.utcnow().isoformat() + 'Z'  # 'Z' indicates UTC time
Domain = <insert domain here >
delegated_credentials = None
http = None
service = None

Cal_List = []
Cal_Name = []


def get_cred(name):
    email = name + "@" + Domain
    eq = "="*len(email)
    print(eq + "\n" + email + "\n" + eq)
    # delegated credentials because we're using a service account
    global delegated_credentials
    delegated_credentials = Credentials.create_delegated(email)
    global http
    http = delegated_credentials.authorize(httplib2.Http())
    global service
    service = discovery.build('calendar', 'v3', http=http)


# Function to get and print all the calendars that a user is subscribed to
def cal_get(name):
    get_cred(name)
    # get the info. specifically it's the 'items' list we need from this dict
    calendar = service.calendarList().list().execute()
    calitems = str(calendar['items']).split(',')
    # print(calitems)
    for i in calitems:
        x = i.replace("'", '').replace('{', '').replace('}', '')
        if str(x).startswith(" id"):
            x = x.split(':')
            Cal_List.append(x[1][1:])
        if str(x).startswith(" summary:"):
            x = x.split(':')
            Cal_Name.append(x[1][1:])


def cal_share(name):
    get_cred(name)
    for index, item in enumerate(Cal_List):
        try:
            rule = service.acl().list(calendarId=item).execute()
            rule2 = rule['items']
            for acl in rule2:
                acl_usr = acl['id']
                acl_role = acl['role']
                acl_sum = Cal_Name[index]
                print(acl_sum + " | " + acl_usr + " | " + acl_role)
        except:
            print('')


# Function to get a list of usable users to use
def get_users():
    users = []
    raw = subprocess.check_output("getent passwd", shell=True)
    line = str(raw).split(":")
    for s in line:
        if s.startswith("/home"):
            users.append(str(s)[6:])
    # users.sort()
    for u in users:
        try:
            cal_get(u)
            cal_share(u)
        except:
            print("No calendars for " + u)

if str(users_ret) == "all":
    get_users()
else:
    cal_get(str(users_ret))
    cal_share(str(users_ret))
