#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 24 17:27:10 2017

@author: rharvison
"""

import os

mach = ["mate-terminal "]



def connect():
    
#    f = os.popen("nmap -sn 172.27.1.0/21")
    f = os.popen("ruptime|grep -v work| grep -v render | grep -v dev | grep -v player | grep -v compo")
    
    for line in f.readlines():
        out = line.split()      
        trgt = "--tab -e 'bash -ic ssh' " + str(out[0] + " ")
        mach.append(trgt)





connect()

str1 = ''.join(mach)
print(str1)

e = os.popen(str1)